// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: keymanager.proto

package kmspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionType int32

const (
	SessionType_SESSION_TYPE_UNSPECIFIED SessionType = 0
	SessionType_SESSION_TYPE_KEYGEN      SessionType = 1
	SessionType_SESSION_TYPE_SIGN        SessionType = 2
	SessionType_SESSION_TYPE_RESHARE     SessionType = 3
)

// Enum value maps for SessionType.
var (
	SessionType_name = map[int32]string{
		0: "SESSION_TYPE_UNSPECIFIED",
		1: "SESSION_TYPE_KEYGEN",
		2: "SESSION_TYPE_SIGN",
		3: "SESSION_TYPE_RESHARE",
	}
	SessionType_value = map[string]int32{
		"SESSION_TYPE_UNSPECIFIED": 0,
		"SESSION_TYPE_KEYGEN":      1,
		"SESSION_TYPE_SIGN":        2,
		"SESSION_TYPE_RESHARE":     3,
	}
)

func (x SessionType) Enum() *SessionType {
	p := new(SessionType)
	*p = x
	return p
}

func (x SessionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionType) Descriptor() protoreflect.EnumDescriptor {
	return file_keymanager_proto_enumTypes[0].Descriptor()
}

func (SessionType) Type() protoreflect.EnumType {
	return &file_keymanager_proto_enumTypes[0]
}

func (x SessionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionType.Descriptor instead.
func (SessionType) EnumDescriptor() ([]byte, []int) {
	return file_keymanager_proto_rawDescGZIP(), []int{0}
}

type StartSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Type          SessionType            `protobuf:"varint,2,opt,name=type,proto3,enum=signet.kms.v1.SessionType" json:"type,omitempty"`
	Params        []byte                 `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"` // session-type-specific params (see below)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_keymanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_keymanager_proto_rawDescGZIP(), []int{0}
}

func (x *StartSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartSessionRequest) GetType() SessionType {
	if x != nil {
		return x.Type
	}
	return SessionType_SESSION_TYPE_UNSPECIFIED
}

func (x *StartSessionRequest) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

type StartSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First-round outgoing messages the node should broadcast to peers.
	Outgoing      []*SessionMessage `protobuf:"bytes,1,rep,name=outgoing,proto3" json:"outgoing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_keymanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_keymanager_proto_rawDescGZIP(), []int{1}
}

func (x *StartSessionResponse) GetOutgoing() []*SessionMessage {
	if x != nil {
		return x.Outgoing
	}
	return nil
}

type SessionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`       // sender PartyID
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`           // recipient PartyID; empty = broadcast
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // opaque FROST round message bytes
	Result        *SessionResult         `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`   // set on the final message before stream close
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMessage) Reset() {
	*x = SessionMessage{}
	mi := &file_keymanager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMessage) ProtoMessage() {}

func (x *SessionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMessage.ProtoReflect.Descriptor instead.
func (*SessionMessage) Descriptor() ([]byte, []int) {
	return file_keymanager_proto_rawDescGZIP(), []int{2}
}

func (x *SessionMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SessionMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SessionMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SessionMessage) GetResult() *SessionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// SessionResult carries the output of a completed session. The KMS populates
// this on the last SessionMessage it sends before closing the ProcessMessage
// stream.
type SessionResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SignatureR     []byte                 `protobuf:"bytes,1,opt,name=signature_r,json=signatureR,proto3" json:"signature_r,omitempty"`             // 33-byte compressed R (sign sessions)
	SignatureZ     []byte                 `protobuf:"bytes,2,opt,name=signature_z,json=signatureZ,proto3" json:"signature_z,omitempty"`             // 32-byte scalar z (sign sessions)
	GroupKey       []byte                 `protobuf:"bytes,3,opt,name=group_key,json=groupKey,proto3" json:"group_key,omitempty"`                   // 33-byte compressed group pubkey (keygen sessions)
	VerifyingShare []byte                 `protobuf:"bytes,4,opt,name=verifying_share,json=verifyingShare,proto3" json:"verifying_share,omitempty"` // this node's public key share (keygen sessions)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionResult) Reset() {
	*x = SessionResult{}
	mi := &file_keymanager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResult) ProtoMessage() {}

func (x *SessionResult) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResult.ProtoReflect.Descriptor instead.
func (*SessionResult) Descriptor() ([]byte, []int) {
	return file_keymanager_proto_rawDescGZIP(), []int{3}
}

func (x *SessionResult) GetSignatureR() []byte {
	if x != nil {
		return x.SignatureR
	}
	return nil
}

func (x *SessionResult) GetSignatureZ() []byte {
	if x != nil {
		return x.SignatureZ
	}
	return nil
}

func (x *SessionResult) GetGroupKey() []byte {
	if x != nil {
		return x.GroupKey
	}
	return nil
}

func (x *SessionResult) GetVerifyingShare() []byte {
	if x != nil {
		return x.VerifyingShare
	}
	return nil
}

type AbortSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortSessionRequest) Reset() {
	*x = AbortSessionRequest{}
	mi := &file_keymanager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortSessionRequest) ProtoMessage() {}

func (x *AbortSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortSessionRequest.ProtoReflect.Descriptor instead.
func (*AbortSessionRequest) Descriptor() ([]byte, []int) {
	return file_keymanager_proto_rawDescGZIP(), []int{4}
}

func (x *AbortSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AbortSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortSessionResponse) Reset() {
	*x = AbortSessionResponse{}
	mi := &file_keymanager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortSessionResponse) ProtoMessage() {}

func (x *AbortSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortSessionResponse.ProtoReflect.Descriptor instead.
func (*AbortSessionResponse) Descriptor() ([]byte, []int) {
	return file_keymanager_proto_rawDescGZIP(), []int{5}
}

type KeyRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       []byte                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // 32-byte group identifier
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Curve         string                 `protobuf:"bytes,3,opt,name=curve,proto3" json:"curve,omitempty"` // "secp256k1" or "ed25519"; empty defaults to "secp256k1"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRef) Reset() {
	*x = KeyRef{}
	mi := &file_keymanager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRef) ProtoMessage() {}

func (x *KeyRef) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRef.ProtoReflect.Descriptor instead.
func (*KeyRef) Descriptor() ([]byte, []int) {
	return file_keymanager_proto_rawDescGZIP(), []int{6}
}

func (x *KeyRef) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *KeyRef) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *KeyRef) GetCurve() string {
	if x != nil {
		return x.Curve
	}
	return ""
}

type GroupRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       []byte                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupRef) Reset() {
	*x = GroupRef{}
	mi := &file_keymanager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRef) ProtoMessage() {}

func (x *GroupRef) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRef.ProtoReflect.Descriptor instead.
func (*GroupRef) Descriptor() ([]byte, []int) {
	return file_keymanager_proto_rawDescGZIP(), []int{7}
}

func (x *GroupRef) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

type PublicKeyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GroupKey       []byte                 `protobuf:"bytes,1,opt,name=group_key,json=groupKey,proto3" json:"group_key,omitempty"`                   // compressed group public key (33 bytes secp256k1, 32 bytes Ed25519)
	VerifyingShare []byte                 `protobuf:"bytes,2,opt,name=verifying_share,json=verifyingShare,proto3" json:"verifying_share,omitempty"` // this node's public key share
	Generation     uint64                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	Scope          []byte                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"` // signing scope constraint (empty = unscoped)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PublicKeyResponse) Reset() {
	*x = PublicKeyResponse{}
	mi := &file_keymanager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyResponse) ProtoMessage() {}

func (x *PublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyResponse.ProtoReflect.Descriptor instead.
func (*PublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_keymanager_proto_rawDescGZIP(), []int{8}
}

func (x *PublicKeyResponse) GetGroupKey() []byte {
	if x != nil {
		return x.GroupKey
	}
	return nil
}

func (x *PublicKeyResponse) GetVerifyingShare() []byte {
	if x != nil {
		return x.VerifyingShare
	}
	return nil
}

func (x *PublicKeyResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *PublicKeyResponse) GetScope() []byte {
	if x != nil {
		return x.Scope
	}
	return nil
}

type KeyListEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Curve         string                 `protobuf:"bytes,2,opt,name=curve,proto3" json:"curve,omitempty"` // "secp256k1" or "ed25519"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyListEntry) Reset() {
	*x = KeyListEntry{}
	mi := &file_keymanager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyListEntry) ProtoMessage() {}

func (x *KeyListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyListEntry.ProtoReflect.Descriptor instead.
func (*KeyListEntry) Descriptor() ([]byte, []int) {
	return file_keymanager_proto_rawDescGZIP(), []int{9}
}

func (x *KeyListEntry) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *KeyListEntry) GetCurve() string {
	if x != nil {
		return x.Curve
	}
	return ""
}

type KeyListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*KeyListEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyListResponse) Reset() {
	*x = KeyListResponse{}
	mi := &file_keymanager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyListResponse) ProtoMessage() {}

func (x *KeyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyListResponse.ProtoReflect.Descriptor instead.
func (*KeyListResponse) Descriptor() ([]byte, []int) {
	return file_keymanager_proto_rawDescGZIP(), []int{10}
}

func (x *KeyListResponse) GetEntries() []*KeyListEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CommitReshareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"` // the new active generation after commit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitReshareResponse) Reset() {
	*x = CommitReshareResponse{}
	mi := &file_keymanager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitReshareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitReshareResponse) ProtoMessage() {}

func (x *CommitReshareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitReshareResponse.ProtoReflect.Descriptor instead.
func (*CommitReshareResponse) Descriptor() ([]byte, []int) {
	return file_keymanager_proto_rawDescGZIP(), []int{11}
}

func (x *CommitReshareResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type DiscardPendingReshareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscardPendingReshareResponse) Reset() {
	*x = DiscardPendingReshareResponse{}
	mi := &file_keymanager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscardPendingReshareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardPendingReshareResponse) ProtoMessage() {}

func (x *DiscardPendingReshareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardPendingReshareResponse.ProtoReflect.Descriptor instead.
func (*DiscardPendingReshareResponse) Descriptor() ([]byte, []int) {
	return file_keymanager_proto_rawDescGZIP(), []int{12}
}

type RollbackReshareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       []byte                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"` // target generation to restore
	Curve         string                 `protobuf:"bytes,4,opt,name=curve,proto3" json:"curve,omitempty"`            // "secp256k1" or "ed25519"; empty defaults to "secp256k1"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackReshareRequest) Reset() {
	*x = RollbackReshareRequest{}
	mi := &file_keymanager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackReshareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackReshareRequest) ProtoMessage() {}

func (x *RollbackReshareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackReshareRequest.ProtoReflect.Descriptor instead.
func (*RollbackReshareRequest) Descriptor() ([]byte, []int) {
	return file_keymanager_proto_rawDescGZIP(), []int{13}
}

func (x *RollbackReshareRequest) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *RollbackReshareRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *RollbackReshareRequest) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *RollbackReshareRequest) GetCurve() string {
	if x != nil {
		return x.Curve
	}
	return ""
}

type RollbackReshareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackReshareResponse) Reset() {
	*x = RollbackReshareResponse{}
	mi := &file_keymanager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackReshareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackReshareResponse) ProtoMessage() {}

func (x *RollbackReshareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keymanager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackReshareResponse.ProtoReflect.Descriptor instead.
func (*RollbackReshareResponse) Descriptor() ([]byte, []int) {
	return file_keymanager_proto_rawDescGZIP(), []int{14}
}

var File_keymanager_proto protoreflect.FileDescriptor

const file_keymanager_proto_rawDesc = "" +
	"\n" +
	"\x10keymanager.proto\x12\rsignet.kms.v1\"|\n" +
	"\x13StartSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.signet.kms.v1.SessionTypeR\x04type\x12\x16\n" +
	"\x06params\x18\x03 \x01(\fR\x06params\"Q\n" +
	"\x14StartSessionResponse\x129\n" +
	"\boutgoing\x18\x01 \x03(\v2\x1d.signet.kms.v1.SessionMessageR\boutgoing\"\xa3\x01\n" +
	"\x0eSessionMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x124\n" +
	"\x06result\x18\x05 \x01(\v2\x1c.signet.kms.v1.SessionResultR\x06result\"\x97\x01\n" +
	"\rSessionResult\x12\x1f\n" +
	"\vsignature_r\x18\x01 \x01(\fR\n" +
	"signatureR\x12\x1f\n" +
	"\vsignature_z\x18\x02 \x01(\fR\n" +
	"signatureZ\x12\x1b\n" +
	"\tgroup_key\x18\x03 \x01(\fR\bgroupKey\x12'\n" +
	"\x0fverifying_share\x18\x04 \x01(\fR\x0everifyingShare\"4\n" +
	"\x13AbortSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x16\n" +
	"\x14AbortSessionResponse\"P\n" +
	"\x06KeyRef\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\fR\agroupId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x14\n" +
	"\x05curve\x18\x03 \x01(\tR\x05curve\"%\n" +
	"\bGroupRef\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\fR\agroupId\"\x8f\x01\n" +
	"\x11PublicKeyResponse\x12\x1b\n" +
	"\tgroup_key\x18\x01 \x01(\fR\bgroupKey\x12'\n" +
	"\x0fverifying_share\x18\x02 \x01(\fR\x0everifyingShare\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\fR\x05scope\";\n" +
	"\fKeyListEntry\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x14\n" +
	"\x05curve\x18\x02 \x01(\tR\x05curve\"H\n" +
	"\x0fKeyListResponse\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.signet.kms.v1.KeyListEntryR\aentries\"7\n" +
	"\x15CommitReshareResponse\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\"\x1f\n" +
	"\x1dDiscardPendingReshareResponse\"\x80\x01\n" +
	"\x16RollbackReshareRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\fR\agroupId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\x12\x14\n" +
	"\x05curve\x18\x04 \x01(\tR\x05curve\"\x19\n" +
	"\x17RollbackReshareResponse*u\n" +
	"\vSessionType\x12\x1c\n" +
	"\x18SESSION_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SESSION_TYPE_KEYGEN\x10\x01\x12\x15\n" +
	"\x11SESSION_TYPE_SIGN\x10\x02\x12\x18\n" +
	"\x14SESSION_TYPE_RESHARE\x10\x032\xae\x05\n" +
	"\n" +
	"KeyManager\x12W\n" +
	"\fStartSession\x12\".signet.kms.v1.StartSessionRequest\x1a#.signet.kms.v1.StartSessionResponse\x12R\n" +
	"\x0eProcessMessage\x12\x1d.signet.kms.v1.SessionMessage\x1a\x1d.signet.kms.v1.SessionMessage(\x010\x01\x12W\n" +
	"\fAbortSession\x12\".signet.kms.v1.AbortSessionRequest\x1a#.signet.kms.v1.AbortSessionResponse\x12L\n" +
	"\rCommitReshare\x12\x15.signet.kms.v1.KeyRef\x1a$.signet.kms.v1.CommitReshareResponse\x12\\\n" +
	"\x15DiscardPendingReshare\x12\x15.signet.kms.v1.KeyRef\x1a,.signet.kms.v1.DiscardPendingReshareResponse\x12`\n" +
	"\x0fRollbackReshare\x12%.signet.kms.v1.RollbackReshareRequest\x1a&.signet.kms.v1.RollbackReshareResponse\x12G\n" +
	"\fGetPublicKey\x12\x15.signet.kms.v1.KeyRef\x1a .signet.kms.v1.PublicKeyResponse\x12C\n" +
	"\bListKeys\x12\x17.signet.kms.v1.GroupRef\x1a\x1e.signet.kms.v1.KeyListResponseB\x12Z\x10signet/kms/kmspbb\x06proto3"

var (
	file_keymanager_proto_rawDescOnce sync.Once
	file_keymanager_proto_rawDescData []byte
)

func file_keymanager_proto_rawDescGZIP() []byte {
	file_keymanager_proto_rawDescOnce.Do(func() {
		file_keymanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keymanager_proto_rawDesc), len(file_keymanager_proto_rawDesc)))
	})
	return file_keymanager_proto_rawDescData
}

var file_keymanager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_keymanager_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_keymanager_proto_goTypes = []any{
	(SessionType)(0),                      // 0: signet.kms.v1.SessionType
	(*StartSessionRequest)(nil),           // 1: signet.kms.v1.StartSessionRequest
	(*StartSessionResponse)(nil),          // 2: signet.kms.v1.StartSessionResponse
	(*SessionMessage)(nil),                // 3: signet.kms.v1.SessionMessage
	(*SessionResult)(nil),                 // 4: signet.kms.v1.SessionResult
	(*AbortSessionRequest)(nil),           // 5: signet.kms.v1.AbortSessionRequest
	(*AbortSessionResponse)(nil),          // 6: signet.kms.v1.AbortSessionResponse
	(*KeyRef)(nil),                        // 7: signet.kms.v1.KeyRef
	(*GroupRef)(nil),                      // 8: signet.kms.v1.GroupRef
	(*PublicKeyResponse)(nil),             // 9: signet.kms.v1.PublicKeyResponse
	(*KeyListEntry)(nil),                  // 10: signet.kms.v1.KeyListEntry
	(*KeyListResponse)(nil),               // 11: signet.kms.v1.KeyListResponse
	(*CommitReshareResponse)(nil),         // 12: signet.kms.v1.CommitReshareResponse
	(*DiscardPendingReshareResponse)(nil), // 13: signet.kms.v1.DiscardPendingReshareResponse
	(*RollbackReshareRequest)(nil),        // 14: signet.kms.v1.RollbackReshareRequest
	(*RollbackReshareResponse)(nil),       // 15: signet.kms.v1.RollbackReshareResponse
}
var file_keymanager_proto_depIdxs = []int32{
	0,  // 0: signet.kms.v1.StartSessionRequest.type:type_name -> signet.kms.v1.SessionType
	3,  // 1: signet.kms.v1.StartSessionResponse.outgoing:type_name -> signet.kms.v1.SessionMessage
	4,  // 2: signet.kms.v1.SessionMessage.result:type_name -> signet.kms.v1.SessionResult
	10, // 3: signet.kms.v1.KeyListResponse.entries:type_name -> signet.kms.v1.KeyListEntry
	1,  // 4: signet.kms.v1.KeyManager.StartSession:input_type -> signet.kms.v1.StartSessionRequest
	3,  // 5: signet.kms.v1.KeyManager.ProcessMessage:input_type -> signet.kms.v1.SessionMessage
	5,  // 6: signet.kms.v1.KeyManager.AbortSession:input_type -> signet.kms.v1.AbortSessionRequest
	7,  // 7: signet.kms.v1.KeyManager.CommitReshare:input_type -> signet.kms.v1.KeyRef
	7,  // 8: signet.kms.v1.KeyManager.DiscardPendingReshare:input_type -> signet.kms.v1.KeyRef
	14, // 9: signet.kms.v1.KeyManager.RollbackReshare:input_type -> signet.kms.v1.RollbackReshareRequest
	7,  // 10: signet.kms.v1.KeyManager.GetPublicKey:input_type -> signet.kms.v1.KeyRef
	8,  // 11: signet.kms.v1.KeyManager.ListKeys:input_type -> signet.kms.v1.GroupRef
	2,  // 12: signet.kms.v1.KeyManager.StartSession:output_type -> signet.kms.v1.StartSessionResponse
	3,  // 13: signet.kms.v1.KeyManager.ProcessMessage:output_type -> signet.kms.v1.SessionMessage
	6,  // 14: signet.kms.v1.KeyManager.AbortSession:output_type -> signet.kms.v1.AbortSessionResponse
	12, // 15: signet.kms.v1.KeyManager.CommitReshare:output_type -> signet.kms.v1.CommitReshareResponse
	13, // 16: signet.kms.v1.KeyManager.DiscardPendingReshare:output_type -> signet.kms.v1.DiscardPendingReshareResponse
	15, // 17: signet.kms.v1.KeyManager.RollbackReshare:output_type -> signet.kms.v1.RollbackReshareResponse
	9,  // 18: signet.kms.v1.KeyManager.GetPublicKey:output_type -> signet.kms.v1.PublicKeyResponse
	11, // 19: signet.kms.v1.KeyManager.ListKeys:output_type -> signet.kms.v1.KeyListResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_keymanager_proto_init() }
func file_keymanager_proto_init() {
	if File_keymanager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keymanager_proto_rawDesc), len(file_keymanager_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keymanager_proto_goTypes,
		DependencyIndexes: file_keymanager_proto_depIdxs,
		EnumInfos:         file_keymanager_proto_enumTypes,
		MessageInfos:      file_keymanager_proto_msgTypes,
	}.Build()
	File_keymanager_proto = out.File
	file_keymanager_proto_goTypes = nil
	file_keymanager_proto_depIdxs = nil
}
