package node

import (
	"context"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/fxamacker/cbor/v2"
	libp2pnet "github.com/libp2p/go-libp2p/core/network"
	"github.com/libp2p/go-libp2p/core/protocol"
	"go.uber.org/zap"

	"signet/network"
	"signet/tss"
)

const coordProtocol = protocol.ID("/signet/coord/1.0.0")

type coordMsgType uint8

const (
	msgKeygen  coordMsgType = 1
	msgSign    coordMsgType = 2
	msgReshare coordMsgType = 3
)

// coordMsg is sent from the initiating node to each other participant to start
// a keygen or sign session.
//
// GroupID and KeyID identify the key shard in storage. For keygen, the
// internal session string is derived as groupID+":"+keyID. For sign, SignNonce
// (a random string generated by the initiator) is appended to disambiguate
// concurrent signing sessions on the same key.
type coordMsg struct {
	Type coordMsgType `cbor:"1,keyasint"`

	// Both keygen and sign: identify the key.
	GroupID   string     `cbor:"2,keyasint,omitempty"`
	KeyID     string     `cbor:"3,keyasint,omitempty"`
	Parties   []tss.PartyID `cbor:"4,keyasint,omitempty"`
	Threshold int        `cbor:"5,keyasint,omitempty"`

	// Sign only: random nonce generated by initiator so all peers derive the
	// same session protocol ID, plus signing parameters.
	SignNonce   string     `cbor:"6,keyasint,omitempty"`
	Signers     []tss.PartyID `cbor:"7,keyasint,omitempty"`
	MessageHash []byte     `cbor:"8,keyasint,omitempty"`

	// Auth: structured auth proof with ZK proof or auth key certificate,
	// plus session key binding.
	Auth *AuthProof `cbor:"10,keyasint,omitempty"`

	// Reshare only: old and new committee definitions.
	OldParties   []tss.PartyID `cbor:"11,keyasint,omitempty"`
	NewParties   []tss.PartyID `cbor:"12,keyasint,omitempty"`
	NewThreshold int           `cbor:"13,keyasint,omitempty"`
	ReshareNonce string        `cbor:"14,keyasint,omitempty"`
}

// keygenSessionID returns the deterministic internal session string for a keygen.
func keygenSessionID(groupID, keyID string) string {
	return groupID + ":" + keyID
}

// signSessionID returns the internal session string for a sign, incorporating
// a random nonce to allow concurrent signs on the same key.
func signSessionID(groupID, keyID, nonce string) string {
	return groupID + ":" + keyID + ":" + nonce
}

// reshareSessionID returns the internal session string for a reshare.
// The nonce distinguishes concurrent reshare attempts on the same key
// (e.g. coordinator vs on-demand).
func reshareSessionID(groupID, keyID, nonce string) string {
	return groupID + ":reshare:" + keyID + ":" + nonce
}

// registerCoordHandler registers the /signet/coord/1.0.0 stream handler on the
// node's libp2p host.
func (n *Node) registerCoordHandler() {
	n.host.LibP2PHost().SetStreamHandler(coordProtocol, n.handleCoordStream)
}

// handleCoordStream handles an incoming coordination request from an initiator.
// It registers a session stream handler, sends a ready ACK, then runs the
// protocol in a background goroutine.
func (n *Node) handleCoordStream(s libp2pnet.Stream) {
	defer s.Close()

	var msg coordMsg
	if err := cbor.NewDecoder(s).Decode(&msg); err != nil {
		n.log.Warn("coord: decode msg", zap.Error(err))
		return
	}

	// Validate auth if the group has any auth policy configured.
	if n.auth.HasAuthPolicy(msg.GroupID) {
		if msg.Auth == nil {
			n.log.Warn("coord: missing auth",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID))
			return
		}
		keyPrefix, err := n.auth.ValidateAuthProof(n.ctx, msg.GroupID, msg.Auth)
		if err != nil {
			n.log.Warn("coord: invalid auth proof",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID),
				zap.Error(err))
			return
		}
		// Verify request signature against session public key.
		var msgHash []byte
		if msg.Type == msgSign {
			msgHash = msg.MessageHash
		}
		if err := verifyRequestSignature(
			msg.Auth.SessionPub, msg.Auth.RequestSig,
			msg.GroupID, msg.KeyID, msg.Auth.Nonce, msg.Auth.Timestamp,
			msgHash,
		); err != nil {
			n.log.Warn("coord: invalid request signature",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID),
				zap.Error(err))
			return
		}
		// Check nonce uniqueness.
		if err := n.sessions.CheckNonce(msg.Auth.Nonce); err != nil {
			n.log.Warn("coord: nonce replay",
				zap.String("group_id", msg.GroupID),
				zap.String("nonce", msg.Auth.Nonce))
			return
		}
		// Check timestamp freshness.
		ts := time.Unix(int64(msg.Auth.Timestamp), 0)
		if time.Since(ts).Abs() > timestampWindow {
			n.log.Warn("coord: timestamp out of range",
				zap.String("group_id", msg.GroupID),
				zap.Uint64("timestamp", msg.Auth.Timestamp))
			return
		}
		// KeyID must match auth identity prefix.
		if msg.KeyID != keyPrefix && !strings.HasPrefix(msg.KeyID, keyPrefix+":") {
			n.log.Warn("coord: key_id does not match auth identity",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID),
				zap.String("key_prefix", keyPrefix))
			return
		}
	}

	switch msg.Type {
	case msgKeygen:
		if info, _ := n.km.GetKeyInfo(msg.GroupID, msg.KeyID); info != nil {
			n.log.Warn("coord: keygen rejected, key already exists",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID))
			s.Write([]byte{0}) // NACK
			return
		}

		sessID := keygenSessionID(msg.GroupID, msg.KeyID)
		sessCtx, sessCancel := context.WithTimeout(n.ctx, 30*time.Second)
		sn, err := network.NewSessionNetwork(sessCtx, n.host, sessID, msg.Parties)
		if err != nil {
			sessCancel()
			n.log.Error("coord: keygen session network",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID),
				zap.Error(err))
			return
		}

		// Register pending keygen BEFORE ACK so a racing sign coord handler
		// will see the pending flag and wait rather than returning "key not found".
		n.markKeygenPending(msg.GroupID, msg.KeyID)

		// ACK only after registering the session stream handler, so the
		// initiator knows all parties are ready before starting the protocol.
		s.Write([]byte{1})

		go func() {
			defer sessCancel()
			defer sn.Close()
			defer n.markKeygenDone(msg.GroupID, msg.KeyID)
			n.log.Info("coord: keygen started",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID))
			_, err := n.km.RunKeygen(sessCtx, KeygenParams{
				Host:      n.host,
				SN:        sn,
				SessionID: sessID,
				GroupID:   msg.GroupID,
				KeyID:     msg.KeyID,
				Parties:   msg.Parties,
				Threshold: msg.Threshold,
			})
			if err != nil {
				n.log.Error("coord: keygen failed",
					zap.String("group_id", msg.GroupID),
					zap.String("key_id", msg.KeyID),
					zap.Error(err))
				return
			}
			n.log.Info("coord: keygen complete",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID))
		}()

	case msgSign:
		sessID := signSessionID(msg.GroupID, msg.KeyID, msg.SignNonce)
		sessCtx, sessCancel := context.WithTimeout(n.ctx, 30*time.Second)
		sn, err := network.NewSessionNetwork(sessCtx, n.host, sessID, msg.Signers)
		if err != nil {
			sessCancel()
			n.log.Error("coord: sign session network",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID),
				zap.Error(err))
			return
		}
		s.Write([]byte{1})

		go func() {
			defer sessCancel()
			defer sn.Close()
			n.log.Info("coord: sign started",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID))

			// Wait for any pending keygen to finish before attempting to sign.
			info, err := n.awaitKey(msg.GroupID, msg.KeyID, 10*time.Second)
			if err != nil {
				n.log.Error("coord: load config",
					zap.String("group_id", msg.GroupID),
					zap.String("key_id", msg.KeyID),
					zap.Error(err))
				return
			}
			if info == nil {
				n.log.Error("coord: key not found",
					zap.String("group_id", msg.GroupID),
					zap.String("key_id", msg.KeyID))
				return
			}

			_, err = n.km.RunSign(sessCtx, SignParams{
				Host:        n.host,
				SN:          sn,
				SessionID:   sessID,
				GroupID:     msg.GroupID,
				KeyID:       msg.KeyID,
				Signers:     msg.Signers,
				MessageHash: msg.MessageHash,
			})
			if err != nil {
				n.log.Error("coord: sign failed",
					zap.String("group_id", msg.GroupID),
					zap.String("key_id", msg.KeyID),
					zap.Error(err))
				return
			}
			n.log.Info("coord: sign complete",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID))
		}()

	case msgReshare:
		// Reshare is administrative — no auth validation required.
		// Validate that this node knows about the reshare job.
		if n.reshareStore == nil {
			n.log.Warn("coord: reshare rejected, reshare store not initialized")
			s.Write([]byte{0})
			return
		}

		job, err := n.reshareStore.GetJob(msg.GroupID)
		if err != nil || job == nil {
			n.log.Warn("coord: reshare rejected, no reshare job for group",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID))
			s.Write([]byte{0})
			return
		}

		// Check if this key is already done for this job.
		done, _ := n.reshareStore.IsKeyDone(msg.GroupID, msg.KeyID)
		if done {
			// Key already reshared — ACK but no-op (handles coordinator/on-demand race).
			s.Write([]byte{1})
			return
		}

		// Check/register per-key reshare channel. If another session is
		// already running for this key, NACK to avoid duplicates.
		if !n.tryRegisterReshareKey(msg.GroupID, msg.KeyID) {
			n.log.Debug("coord: reshare NACK, session already running",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID))
			s.Write([]byte{0})
			return
		}

		allParties := msg.Parties // old ∪ new
		sessID := reshareSessionID(msg.GroupID, msg.KeyID, msg.ReshareNonce)
		sessCtx, sessCancel := context.WithTimeout(n.ctx, 30*time.Second)
		sn, err := network.NewSessionNetwork(sessCtx, n.host, sessID, allParties)
		if err != nil {
			sessCancel()
			n.completeReshareKey(msg.GroupID, msg.KeyID, false)
			n.log.Error("coord: reshare session network",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID),
				zap.Error(err))
			return
		}

		s.Write([]byte{1})

		go func() {
			defer sessCancel()
			defer sn.Close()

			n.log.Info("coord: reshare started",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID))

			result, err := n.km.RunReshare(sessCtx, ReshareParams{
				Host:         n.host,
				SN:           sn,
				SessionID:    sessID,
				GroupID:      msg.GroupID,
				KeyID:        msg.KeyID,
				OldParties:   msg.OldParties,
				NewParties:   msg.NewParties,
				OldThreshold: msg.Threshold,
				NewThreshold: msg.NewThreshold,
			})
			if err != nil {
				n.completeReshareKey(msg.GroupID, msg.KeyID, false)
				n.log.Error("coord: reshare failed",
					zap.String("group_id", msg.GroupID),
					zap.String("key_id", msg.KeyID),
					zap.Error(err))
				return
			}

			// Record completion.
			n.reshareStore.PutKeyDone(msg.GroupID, msg.KeyID, &ReshareKeyRecord{
				CompletedAt: time.Now(),
				ByNode:      string(n.host.Self()),
				OldOnly:     result.OldOnly,
			})
			n.completeReshareKey(msg.GroupID, msg.KeyID, true)

			n.log.Info("coord: reshare complete",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID),
				zap.Bool("old_only", result.OldOnly),
				zap.Uint64("generation", result.Generation))
		}()

	default:
		n.log.Warn("coord: unknown msg type", zap.Uint8("type", uint8(msg.Type)))
	}
}

// broadcastCoord sends msg to each party in targets (excluding self) over a
// direct libp2p stream, and waits for a ready ACK from each. Peer streams are
// opened in parallel so the total latency is bounded by the slowest peer rather
// than the sum of all peers.
func (n *Node) broadcastCoord(ctx context.Context, targets []tss.PartyID, msg coordMsg) error {
	self := n.host.Self()

	payload, err := cbor.Marshal(msg)
	if err != nil {
		return fmt.Errorf("marshal coord msg: %w", err)
	}

	type result struct {
		party tss.PartyID
		err   error
	}

	var peers []tss.PartyID
	for _, pid := range targets {
		if pid != self {
			peers = append(peers, pid)
		}
	}

	ch := make(chan result, len(peers))
	for _, pid := range peers {
		pid := pid
		peerID, ok := n.host.PeerForParty(pid)
		if !ok {
			return fmt.Errorf("no connected peer for party %s", pid)
		}
		go func() {
			s, err := n.host.LibP2PHost().NewStream(ctx, peerID, coordProtocol)
			if err != nil {
				ch <- result{pid, fmt.Errorf("coord stream to %s: %w", pid, err)}
				return
			}
			defer s.Close()
			if _, err := s.Write(payload); err != nil {
				ch <- result{pid, fmt.Errorf("write coord to %s: %w", pid, err)}
				return
			}
			ack := make([]byte, 1)
			if _, err := io.ReadFull(s, ack); err != nil {
				ch <- result{pid, fmt.Errorf("ack from %s: %w", pid, err)}
				return
			}
			if ack[0] == 0 {
				ch <- result{pid, fmt.Errorf("rejected by %s", pid)}
				return
			}
			ch <- result{pid, nil}
		}()
	}

	for range peers {
		r := <-ch
		if r.err != nil {
			return r.err
		}
		n.log.Debug("coord: party ready", zap.String("party", string(r.party)))
	}

	return nil
}
